// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo4LN39fb23xgecHJUJlModv0NZwhv4-8',
    appId: '1:143041710240:web:21fc567055f1dc81ac61c5',
    messagingSenderId: '143041710240',
    projectId: 'adobeshortcuts-ae039',
    authDomain: 'adobeshortcuts-ae039.firebaseapp.com',
    storageBucket: 'adobeshortcuts-ae039.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeSwgWpn2uJ4iwLfvHxGMHRfxotM-bY-U',
    appId: '1:143041710240:android:a6a7aa16a1e6171fac61c5',
    messagingSenderId: '143041710240',
    projectId: 'adobeshortcuts-ae039',
    storageBucket: 'adobeshortcuts-ae039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NlwXgs2F6CVW8Wx-hVTCP2QiUdPPYIM',
    appId: '1:143041710240:ios:97757529997881a5ac61c5',
    messagingSenderId: '143041710240',
    projectId: 'adobeshortcuts-ae039',
    storageBucket: 'adobeshortcuts-ae039.firebasestorage.app',
    iosBundleId: 'com.example.adobeshortcuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_NlwXgs2F6CVW8Wx-hVTCP2QiUdPPYIM',
    appId: '1:143041710240:ios:97757529997881a5ac61c5',
    messagingSenderId: '143041710240',
    projectId: 'adobeshortcuts-ae039',
    storageBucket: 'adobeshortcuts-ae039.firebasestorage.app',
    iosBundleId: 'com.example.adobeshortcuts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo4LN39fb23xgecHJUJlModv0NZwhv4-8',
    appId: '1:143041710240:web:e3ff848b2c2e7336ac61c5',
    messagingSenderId: '143041710240',
    projectId: 'adobeshortcuts-ae039',
    authDomain: 'adobeshortcuts-ae039.firebaseapp.com',
    storageBucket: 'adobeshortcuts-ae039.firebasestorage.app',
  );
}
